name: Nodejs CICD

on:
  push: 
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: [16.x]
  
    steps:
      - run: echo "done"